# site settings
title: Roopkatha Dam
subtitle: Senior Copywriter | Filmmaker | Creative Strategist
email: roopkathaforever@gmail.com
description: Creative Strategist at Dentsu Network with 3+ years experience working with brands like Reliance Retail, Hoichoi, SVF, TATA, and Sony Music. <br />Turning briefs into award-worthy stories that people actually want to watch.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Roopkatha Dam
street_address:
city: Kolkata
state: West Bengal
zip_code:
country: India
phone: 8902271191 / 8240215159

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/roopkatha-dam-b25824154/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
